### ISSUE TITLE
new version v1.1.1 was not fully released 

### ISSUE THREAD

**Issue by a-mnich** [bubkoo/update-authors#3]
Some days ago the PR #2 was merged and other changes were made.
After that, the git tag for the new version v.1.1.1 has been created, but there is no new release in the repository.  
Therefore the new version of the action currently can not be used in workflows.
  
Could you maybe trigger a new release?
### Current Behavior
V1.1.1 is not available for use in Github workflows  
  
![grafik](https://user-images.githubusercontent.com/56564725/213923734-6d8bec6d-85ae-4a03-b8d0-5f35cea66773.png)
![grafik](https://user-images.githubusercontent.com/56564725/213923907-e1af0812-4d90-486e-8864-14b1132efe4e.png)
![grafik](https://user-images.githubusercontent.com/56564725/213923920-698c83b8-83d1-4c94-82db-628969e21590.png)

### Possible Solution
- trigger a new release

**Comment by bubkoo** [comment]
@a-mnich v1.1.4 was publised to marketplace.
